;;(set-frame-parameter nil 'unsplittable t)
(defalias 'yes-or-no-p #'y-or-n-p)
(setq frame-resize-pixelwise t)
(global-auto-revert-mode 1)
(global-visual-line-mode t)
(global-font-lock-mode 1)
(electric-pair-mode 1)
(global-linum-mode 1)
(show-paren-mode 1)
(scroll-bar-mode 1)
(tool-bar-mode -1)
(menu-bar-mode 1)
